### ISSUE TITLE
Dropbox login page cant paste password

### ISSUE THREAD

**Issue by Dnkhatri** [Exlaza/CalibreCarte#18]
Why is the Dropbox login page so restrictive. I am unable to login by copy pasting my password. This makes it very hard to login I know its a probably a one time thing so most users forget about it once they connect the app or they are using very easy passwords. I thought I should post this before you guys add more cloud services. I installed the app after your reddit thread but I still haven't used it as it's to cumbersome to actually connect the app.

**Comment by PrernaD** [comment]
Official flutter web view is very restricted but it is the official package so we were using it. We are now thinking of migrating to another package till it gets more stable (we plan to do this in the next release).

**Comment by Exlaza** [comment]
This should be fixed after the latest update. Web view is now removed completely and the login happens in the system browser itself. So any bugs related to web view should be now fixed.
