### ISSUE TITLE
App removed from Play Store

### ISSUE THREAD

**Issue by mendhak** [Exlaza/CalibreCarte#31]
Hi team, the app has been removed from the Play Store. Any plans on bringing it back, if the app is still being developed/maintained?

**Comment by PrernaD** [comment]
Hey, 
We both have moved on to hectic jobs and hence have taken down the app. We might decide to work on it again if we have time in life, can't promise anything though.

**Comment by mendhak** [comment]
Cheers and understood, life happens!
